Manual test checklist
openscilab/nava pull request #43
Opened 2024-04-18 04:53 UTC by sadrasabouri

#### What does this implement/fix? Explain your changes.
Before this we used to add the checklist for local test on different OSs manually to the pull request comments. From now on after this pull request, that checklist will be part of the pull request template.

2024-04-19 23:53 UTC, sepandhaghighi requested changes
@sadrasabouri Please take a look at my comments 🔥

2024-04-19 23:53 UTC, sepandhaghighi commented on CHANGELOG.md
> +- OSs local check added to pull request template
- OSs local checklist added to pull request template

2024-04-19 23:53 UTC, sepandhaghighi commented on .github/PULL_REQUEST_TEMPLATE.md
> +## Local tests on OSs
I would like to suggest a solution based on the currently available facilities.

- [ ] MacOS
    - [ ] Sonoma
- [ ] Windows
    - [ ] Windows 11
- [ ] Linux
    - [ ] Ubuntu 20.04

2024-04-20 00:05 UTC, sadrasabouri commented
Kindly please re-review @sepandhaghighi

2024-04-20 06:45 UTC, sepandhaghighi approved these changes
🚀

2024-04-20 06:45 UTC, merged